### ISSUE TITLE
Creating invitations work, but querying them does not

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#1]
I mutate an invitation like this:

> {
	"query": "mutation AddMember($groupId: String!, $name: String!, $createInvite: Boolean!) {  
                groupAddMember(groupId: $groupId, name: $name, createInvite: $createInvite) {    
                 __typename    command    id    correlationId  }}",
                	"operationName": "AddMember",
                	"variables": {
		"groupId": "5b961d3299b5e30002bfb118",
		"name": "Adri Smuts",
		"createInvite": true
	}
}

Then I get the result back like this:

> {
	"data": {
		"groupAddMember": [{
			"__typename": "Command",
			"command": "GroupInviteMemberRequest",
			"id": "5b961e2ee8bdf50002e60328",
			"correlationId": "50d064b3a16e43ef8c642c3df0ce49e1"
		}, {
			"__typename": "Command",
			"command": "UserConnectionCreateRequest",
			"id": "5b961e2ee8bdf50002e60328",
			"correlationId": "50d064b3a16e43ef8c642c3df0ce49e1"
		}]
	}
}

and then I use the id (5b961e2ee8bdf50002e60328) to create the invitation.

I log out and sign in as a different user and open the invitation, which results in this query:

> {
	"query": "query Invitation($id: String!) {  userInviteByPublicId(id: $id) {    __typename    id    name    expires    invitingUser {      __typename      name    }  }}",
	"operationName": "Invitation",
	"variables": {
		"id": "5b961e2ee8bdf50002e60328"
	}
}

with this result

> {"data":{"userInviteByPublicId":null}}

Please advise.

**Comment by rolfwessels** [comment]
So I will try to explain. There are public ids and internal id for invitations. There are some technical reasons for this. The *internal id* that we use is only random(ISH) so I want to store them with this Id for lookup but I also want a *public ID* that is more random and will go to the customer.

With this in mind there are two ways to find the user invite after you made the call

## The longway.

1) Call `groupAddMember`
2) Capture *id* given on the `UserConnectionCreateRequest` command (actually irrelative which id you use because they are the same.
3) Use that ID that was captured with `userInviteById` to get the record (note the *byId*). You can then use the public id on the invite record to be sent to the customer. The public id is the random guid and the one that is used when registering or joining a group. It is not the internal ID

## The shortcut. 
1) Call the `groupAddMember`
2) Capture the *correlationId*
3) Send invite with 'correlationId'. This is because I reuse the random correlationId to make the public ID. This shortcut allow the invite to be sent without having to make another call.


The `userInviteByPublicId` call is when the invited customer is loaded and you as client want to check it the invite has been used and is still active.

**Comment by rolfwessels** [comment]
I have to add that in hind sight I might have over engineerd this :-). I could have done everything on the public id. 

I'm happy to simplyfi this but that might break IOS :-/

**Comment by JacquesSmuts** [comment]
Switching to correlationId worked. Thank you.
