### ISSUE TITLE
Payments Extract process

### ISSUE THREAD

**Issue by richardhartley101** [kin-business/kin.api.public#13]
Often the pages suddenly go slow/look like they are hanging - for example the in app settlement page or main dashboard page (or breaks: "Failed to read transactionInAppSettlements from service.")
    Page load: Load the page with rows "unticked" - i.e. not ready for payment
    Please add one of those annoying "are you sure you want to pay alerts when you click pay"
    Download: Need ability to download only records needing to be processed

**Comment by rolfwessels** [comment]
* The slow bit we know about and we are working on improving the performance. (The errors should be fixed now, if you see them again please let me know.)

* Unchecked done

* As discussed  because they start off unticked we don't need the confirmation box anymore

* This can already be done, just un tick the 'Show Completed'

**Comment by rolfwessels** [comment]
@richardhartley101 This is now on develop. Please let me know if it works as expected.

**Comment by rolfwessels** [comment]
Closing for now.
