### ISSUE TITLE
Duplicate member in balances list

### ISSUE THREAD

**Issue by a-bresler** [kin-business/kin.api.public#31]
sequence of events that led to x2 Freeman in the list. Freeman invited alon+alonnew to kin and created expense -> signed in as alonnew -> accept invite -> see expense. (All as expected)

Then create group -> add Freeman to group from ‘friends on kin’ list -> add transaction to group -> in balances, now there are two freemans

![Screenshot_20190711_143930_com thekinapp dev](https://user-images.githubusercontent.com/25475628/61052392-942b0480-a3eb-11e9-9ebf-dbbb91263c0d.jpg)

**Comment by rolfwessels** [comment]
Thanks, we have discussed this internally and it seems that its a bigger issue. Where invited / active users are becoming ghosts because we require users to accept invites. We are going to investigate having invites to groups for "on kin" users to skip the invite process.

Will let you know when and how it is resolved. 

Thanks for posting the issue

**Comment by rolfwessels** [comment]
Resolved. We now allow you to directly add friends to a new group without invite process
